# Generated by Django 3.1.5 on 2021-02-25 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=25, null=True)),
                ('dp', models.ImageField(blank=True, default='post_images/dp.png', null=True, upload_to='post_images')),
                ('bio', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='post.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post_images')),
                ('caption', models.CharField(default=None, max_length=100)),
                ('git', models.URLField(max_length=128, unique=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.profile')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
